build:
	docker build -t registry.edmodo.io/party94 . 
	
push:
	docker push registry.edmodo.io/party94

run:
	docker run -it -p 5000:5000 registry.edmodo.io/party94:latest 

bash:
	docker run -it -p 5000:5000 registry.edmodo.io/party94:latest bash

launch:
	docker run -p 5000:5000 -d registry.edmodo.io/party94:latest

